q/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import qworld
from qworld import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^quest/', include('qworld.urls')),
    url(r'^profile/', include('user_profile.urls')),
    url(r'^rules/$', qworld.views.rules, name='rules'),
    url(r'^support/$', qworld.views.support, name='support'),
    url(r'^', include('loginsys.urls')),
]

user_profile/urls.py
import user_profile
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from user_profile import views



urlpatterns = [
    url(r'^settings/$',  user_profile.views.settings, name='settings'),
    url(r'^(?P<prof_login>\w+)/$',  user_profile.views.profile, name='profile'),
    url(r'^(?P<prof_login>\w+)/get_money/$',  user_profile.views.get_money),
    url(r'^$',  user_profile.views.profile),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/models.py
import datetime

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from django.db import models


class UserManager(BaseUserManager):

    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('Email непременно должен быть указан')
        if len(username) < 6:
            raise ValueError('Длина логина должна быть больше 5')

        user = self.model(
            email=UserManager.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(username, email, password)
        user.is_superuser = True
        user.is_admin = True
        user.save(using=self._db)
        return user


def user_directory_avatar_path(instance, filename):
    return 'users/avatar/{0}/{1}'.format(instance.username, 'avatar.png')


class ExtUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField('username', max_length=20, unique=True, db_index=True)
    email = models.EmailField('Электронная почта', max_length=30, unique=True, db_index=True)
    level = models.IntegerField('Уровень', default=0, blank=True)
    level_points = models.IntegerField('Очки для уровня', default=0, blank=True)
    avatar = models.ImageField('Аватар', blank=True, upload_to=user_directory_avatar_path,
                               default='default_user_avatar.png')
    firstname = models.CharField('Имя', max_length=40, null=True, blank=True)
    lastname = models.CharField('Фамилия', max_length=40, null=True, blank=True)
    middlename = models.CharField('Отчество', max_length=40, null=True, blank=True)
    money = models.IntegerField('Баланс', default=0)
    date_of_birth = models.DateField('Дата рождения', null=True, blank=True)
    register_date = models.DateField('Дата регистрации', auto_now_add=True)
    phone = models.CharField('Телефон', max_length=15, null=True, blank=True)
    is_active = models.BooleanField('Активен', default=True)
    is_admin = models.BooleanField('Суперпользователь', default=False)
    about_user = models.TextField('О пользователе', blank=True)
    sb_can_rt_com = models.BooleanField(default=True, blank=True,
                                        verbose_name='Кто-нибудь может оставлять коментарии')
    sb_can_wt_quests = models.BooleanField(default=True, blank=True,
                                           verbose_name='Кто-нибудь может смотреть участие и создание квестов')

    # Этот метод обязательно должен быть определён
    def get_full_name(self):
        return self.username

    # Требуется для админки
    @property
    def is_staff(self):
        return self.is_admin

    def get_short_name(self):
        return self.username

    def __str__(self):
        return self.username

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'



class Participated_quest(models.Model):
    class Meta():
        verbose_name_plural = 'Квесты с участием человека'
    quest_id = models.IntegerField()
    for_user = models.ForeignKey(ExtUser)


class Created_quest(models.Model):
    class Meta():
        verbose_name_plural = 'Созданные квесты'
    quest_id = models.IntegerField()
    for_user = models.ForeignKey(ExtUser)


class Waiting_quest(models.Model):
    class Meta():
        verbose_name_plural = 'Неоплаченные квесты'
    quest_id = models.IntegerField()
    for_user = models.ForeignKey(ExtUser)


def user_directory_path(instance, filename):
    return 'users/photos/{0}/{1}'.format(instance.for_user.username, filename)


class User_photo(models.Model):
    class Meta:
        verbose_name_plural = 'Фотографии'

    for_user = models.ForeignKey(ExtUser)
    photo = models.ImageField('Фотография', upload_to=user_directory_path)


class Achievement(models.Model):
    class Meta:
        verbose_name_plural = 'Достижения'

    avatar = models.ImageField('Картинка', upload_to='achievements')
    name = models.CharField('Название ачивки', max_length=100)
    description = models.TextField('Описание')
    max_score = models.IntegerField('Максимальное количество очков', blank=True)

    def __str__(self):
        return self.name


class Achievement_user(models.Model):
    class Meta:
        verbose_name_plural = 'Достяжения пользователя'

    achiev_id = models.IntegerField('id достяжения')
    min_score = models.IntegerField('Сколько сейчас очков', default=0)
    for_user = models.ForeignKey(ExtUser)

user_profile/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from user_profile.models import  ExtUser, User_photo


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Подтверждение',
        widget=forms.PasswordInput
    )

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Пароль и подтверждение не совпадают')
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ('email',)


class UserChangeForm(forms.ModelForm):

    '''
    Форма для обновления данных пользователей. Нужна только для того, чтобы не
    видеть постоянных ошибок "Не заполнено поле password" при обновлении данных
    пользователя.
    '''
    password = ReadOnlyPasswordHashField(
        widget=forms.PasswordInput,
        required=False
    )

    def save(self, commit=True):
        user = super(UserChangeForm, self).save(commit=False)
        password = self.cleaned_data["password"]
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['email', ]


class LoginForm(forms.Form):

    """Форма для входа в систему
    """
    username = forms.CharField()
    password = forms.CharField()


class UserChangeProfileData(forms.Form, forms.ModelForm):
    avatar = forms.FileField(widget=forms.FileInput(), required=False)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = ReadOnlyPasswordHashField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), required=False)

    class Meta:
        model = ExtUser
        fields = ('email', 'username', 'avatar', 'firstname', 'lastname', 'about_user',
                  'middlename', 'date_of_birth', 'phone', 'sb_can_rt_com', 'sb_can_wt_quests')

    def save(self, commit=True):
        change = super(UserChangeProfileData, self).save(commit=False)
        password = self.cleaned_data["password"]
        if password and password != '' and not password.isspace():
            change.set_password(password)
        if commit:
            change.save()
        return change

user_profile/views.py
import os
from django.contrib import auth
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from loginsys.views import validate_image
from q.settings import MEDIA_ROOT, EMAIL_HOST_USER
from qworld.models import Quest
from payment_tranch.models import Application
from user_profile.forms import UserChangeProfileData
from user_profile.models import ExtUser, Participated_quest, Created_quest, User_photo, Achievement_user, \
    Achievement, Waiting_quest
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
Now = timezone.now()


def profile(request, prof_login=''):
    args = {}
    if request.user.is_authenticated():
        if prof_login == '':
            prof_login = auth.get_user(request).username
        prof_id = get_object_or_404(ExtUser, username=prof_login).id
        part_quest = Participated_quest.objects.filter(for_user=prof_id)
        created_quest = Created_quest.objects.filter(for_user=prof_id)
        if prof_id == auth.get_user(request).id:
            list_of_waiting_quest = {}
            waiting_quest = Waiting_quest.objects.all().filter(for_user=prof_id)
            for q in waiting_quest:
                quest = Quest.objects.get(id=q.quest_id)
                list_of_waiting_quest.update({q.quest_id: quest})
                args['wait_quests'] = list_of_waiting_quest
        list_of_part_quest, list_of_created_quest = {}, {}
        k = 0
        for q in part_quest:
            k += 1
            quest = Quest.objects.get(id=q.quest_id)
            quest.key = k
            list_of_part_quest.update({q.quest_id: quest})
        k = 0
        for q in created_quest:
            k += 1
            quest = Quest.objects.get(id=q.quest_id)
            quest.key = k
            list_of_created_quest.update({q.quest_id: quest})
        args['pr_quests'] = list_of_part_quest
        args['cr_quests'] = list_of_created_quest
        args['auth_user'] = auth.get_user(request)
        args['user'] = get_object_or_404(ExtUser, id=prof_id)
        args['level_points'] = int(args['user'].level_points // 10)
        args['user_photos'] = User_photo.objects.all().filter(for_user=prof_id)
        achievement = Achievement_user.objects.all().filter(for_user=auth.get_user(request))
        achievement_list = {}
        for ach in achievement:
            achive = Achievement.objects.get(id=ach.achiev_id)
            ach.achive_per = int((ach.min_score / achive.max_score) * 100)
            achievement_list.update({achive: ach})
        args['user_achievements'] = achievement_list
        return render(request, 'user_profile/profile.html', args)
    else:
        return redirect('/')


def settings(request):
    args = {}
    if request.user.is_authenticated():
        photos = User_photo.objects.all().filter(for_user=auth.get_user(request).id)
        args['auth_user'] = auth.get_user(request)
        user = ExtUser.objects.get(id=auth.get_user(request).id)
        args['Changeform'] = UserChangeProfileData(request.POST or None, instance=user)
        args['level_points'] = int(auth.get_user(request).level_points // 10)
        args['user_photos'] = photos
        if request.POST:
            args['auth_user'] = auth.get_user(request)
            user = ExtUser.objects.get(id=auth.get_user(request).id)
            change_form = UserChangeProfileData(request.POST, request.FILES, instance=user)
            if change_form.is_valid():
                id_photos = set()
                for photo in photos:
                    id_photos.add(photo.id)
                for photo in photos:
                    ph_id = bool(request.POST.get('photo' + str(photo.id), ''))
                    if ph_id and photo.id in id_photos:
                        photo.delete()
                        os.remove(MEDIA_ROOT + '/' + photo.photo.name)
                if request.FILES.get('photos'):
                    request_photos = request.FILES.getlist('photos')
                    length_photos_obj = len(User_photo.objects.all().filter(for_user=auth.get_user(request)))
                    for photo in request_photos:
                        if length_photos_obj <= 9:
                            length_photos_obj += 1
                            ph = User_photo(photo=photo, for_user=auth.get_user(request))
                            ph.save()
                if request.FILES.get('avatar'):
                    if validate_image(request.FILES['avatar']):
                        try:
                            os.remove(MEDIA_ROOT + '/users/avatar/' + user.username + '/avatar.png')
                        except Exception as err:
                            pass
                    else:
                        args['image_error'] = 'Размер изображения не должне привышать 20Кб'
                        return render(request, 'user_profile/settings.html', args)
                attr = {}
                attr['auth_user'] = auth.get_user(request)
                to = auth.get_user(request).email
                subject, from_email = 'Внесение изменений в профиль', EMAIL_HOST_USER
                html_content = get_template('email/user_settings.html').render(Context(attr))
                msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
                msg.attach_alternative(html_content, "text/html")
                msg.send()
                change_form.save()
                if not request.user.is_authenticated():
                    return redirect('/')
                return redirect('profile', auth.get_user(request).username)
            else:
                return render(request, 'user_profile/settings.html', args)
        return render(request, 'user_profile/settings.html', args)
    else:
        return redirect('/')


@csrf_exempt
def get_money(request, prof_login):
    if request.user.is_authenticated():
        if request.POST:
           user = get_object_or_404(ExtUser, username=prof_login)
           if user.id == auth.get_user(request).id:
               if int(request.POST['amount']) <= user.money and user.money != 0:
                   user.money -= int(request.POST['amount'])
                   try:
                       app = Application.objects.get(user_id=user.id, purse=request.POST['purse'])
                       app.amount += int(request.POST['amount'])
                       app.save()
                   except:
                       app = Application(user_id=user.id, amount=int(request.POST['amount']), purse=request.POST['purse'])
                       app.save()
                   user.save()
                   attr = {}
                   attr['money'] = int(request.POST['amount'])
                   attr['purse'] = request.POST['purse']
                   attr['auth_user'] = auth.get_user(request)
                   to = auth.get_user(request).email
                   subject, from_email = 'Отправка заявки на вывод средств', EMAIL_HOST_USER
                   html_content = get_template('email/get_money.html').render(Context(attr))
                   msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
                   msg.attach_alternative(html_content, "text/html")
                   msg.send()
                   return HttpResponse(1)  
               else:
                   return HttpResponse(0)  
    else:
        return redirect('/')

templates/user_profile/settings.html
{% extends 'qworld/base.html' %}
{% block title %}
Настройки
{% endblock %}
{% load staticfiles %}
{% block content %}
    <script type="text/javascript" src="{% static 'all/datepicker/picker.js' %}"></script>
    <script type="text/javascript" src="{% static 'all/datepicker/picker-date.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'all/datepicker/default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'all/datepicker/default.date.css' %}">
    <link rel="stylesheet" href="{% static 'qworld/css/qworldstyle.css' %}">
    <script>
        tinymce.init({
          selector: 'textarea#id_about_user',
          width:'100%',
          height: 300,
          menubar: false,
          theme: 'modern',
          plugins: [
            'advlist autolink lists link preview hr anchor',
            'searchreplace wordcount visualchars',
            'nonbreaking contextmenu directionality',
            'emoticons paste textcolor colorpicker textpattern toc'
          ],
          toolbar1: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link',
          toolbar2: 'preview | forecolor backcolor emoticons',
          image_advtab: false,
          content_css: [
            '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
            '//www.tinymce.com/css/codepen.min.css'
          ]
         });
    </script>
    <form action="" method="POST" class="settings_form" style="width:100%" enctype='multipart/form-data'>
        {% csrf_token %}
        <div class="col-lg-12 mt-2">
            <div class="card card-block">
                <div>
                    <div class="col-lg-4 float-left mb-2">
                        <img id="settimg" src="{{ auth_user.avatar.url }}" alt="User Photo" class="rounded-circle
                        contact-avatar my-2 mx-auto
                        {% if form.avatar.errors or image_error %}
                            error_image
                        {% endif %}
                        " style="height: 110px;width: 110px;">
                        {% if image_error %}
                            <div class="text-center red-text">Размер изображения превышает 20Кб</div>
                        {% endif %}
                        <div class="text-center">
                            <div class="file-field" style="width:auto;">
                                <div class="btn btn-primary file-field_one" style="cursor: pointer">
                                    <span>Загрузить фотографию</span>
                                    {{ Changeform.avatar }}
                                </div>
                            </div>
                        </div>
                        <div class="mt-2">
                            {{ Changeform.sb_can_rt_com }}
                            <label for="id_sb_can_rt_com">Можно оставлять комментарии на странице</label>

                            {{ Changeform.sb_can_wt_quests }}
                            <label for="id_sb_can_wt_quests">Можно просматривать квесты, в которых я участвовал(а) или создал(а)</label>
                        </div>
                    </div>
                    <div class="col-lg-8 float-right">
                        <div class="d-flex flex-row">
                            <div class="user-level pr-2">
                                {{ auth_user.level }}
                            </div>
                            <div style="width:100%;">
                                <div class="grey-text">
                                    {{ auth_user.level_points }} / 1000
                                </div>
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" style="width:{{ level_points }}%"
                                         aria-valuenow="{{ level_points }}" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <!--First column-->
                            <div class="col-md-6">
                                {% if Changeform.username.errors %}
                                    <div class="md-form error_input">
                                        {{ Changeform.username }}
                                        <label for="id_username" data-error="wrong" data-success="right">Логин</label>
                                    </div>
                                {% else %}
                                    <div class="md-form">
                                        {{ Changeform.username }}
                                        <label for="id_username" data-error="wrong" data-success="right">Логин</label>
                                    </div>
                                {% endif %}
                            </div>
                            <!--Second column-->
                            <div class="col-md-6">
                                <div class="md-form">
                                    {{ Changeform.firstname }}
                                    <label for="id_firstname" data-error="wrong" data-success="right">Ваше имя</label>
                                </div>
                            </div>
                        </div>
                        <div class="m-4"></div>
                        <div class="row">
                            <!--First column-->
                            <div class="col-md-6">
                                <div class="md-form">
                                    {{ Changeform.lastname }}
                                    <label for="id_lastname" data-error="wrong" data-success="right">Ваша фамилия</label>
                                </div>
                            </div>
                            <!--Second column-->
                            <div class="col-md-6">
                                <div class="md-form">
                                    {{ Changeform.middlename }}
                                    <label for="id_middlename" data-error="wrong" data-success="right">Ваше отчество</label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <!--First column-->
                            <div class="col-md-6">
                                <div class="md-form">
                                    {{ Changeform.phone }}
                                    <label for="id_phone" data-error="wrong" data-success="right">Ваша номер</label>
                                </div>
                            </div>
                            <!--Second column-->
                            <div class="col-md-6">
                                <div class="md-form">
                                    {{ Changeform.date_of_birth }}
                                    <label for="id_date_of_birth" data-error="wrong" data-success="right">Ваша дата рождения</label>
                                </div>
                            </div>
                        </div>
                        <div class="m-4"></div>
                        <div class="row">
                            <div class="col-md-6">
                                {% if Changeform.email.errors %}
                                    <div class="md-form error_input">
                                        {{ Changeform.email }}
                                        <label for="id_username" data-error="wrong" data-success="right">Ваш email</label>
                                    </div>
                                {% else %}
                                    <div class="md-form">
                                        {{ Changeform.email }}
                                        <label for="id_username" data-error="wrong" data-success="right">Ваш email</label>
                                    </div>
                                {% endif %}
                            </div>
                            <!--Second column-->
                            <div class="col-md-6">
                                {% if form.password.errors %}
                                    <div class="md-form error_input">
                                        {{ Changeform.password }}
                                        <label for="form82" data-error="wrong" data-success="right">Ваш пароль</label>
                                    </div>
                                {% else %}
                                    <div class="md-form">
                                        {{ Changeform.password }}
                                        <label for="form82" data-error="wrong" data-success="right">Ваш пароль</label>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="fixed-action-btn text-right" style="bottom: 45px; right: 24px;">
                            <button class="btn-floating btn-large btn-primary
                            hoverable" data-toggle="tooltip" data-placement="left"
                                    title="Сохранить изменения"><i class="fa fa-save"></i></button>
                        </div>
                        <script>
                            $(function () {
                              $('[data-toggle="tooltip"]').tooltip()
                            })
                        </script>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 mt-2 float-right">
            <div class="card card-block">
                <h4 style="color:#424242" >Фотографии:</h4>
                {% if user_photos %}
                    <div class="grey-text mb-1" style="font-size:0.9rem;">Кликните на фотографии, которые хотите удалить.</div>
                    <div class="w-100 foto_select">
                        {% for user_photo in user_photos %}
                            <input id="{{ user_photo.id }}" name="photo{{ user_photo.id }}" type="checkbox">
                            <label for="{{ user_photo.id }}" class="float-left mb-1 col-md-6" style="padding-left: 0;padding-right: 0">
                                <img src="{{ user_photo.photo.url }}">
                            </label>
                        {% endfor %}
                    </div>
                    <div class="grey-text" style="font-size:0.9rem;margin-top: 0.2rem;">Или загрузите новые.</div>
                    <div id="download_img">

                    </div>
                    <div class="file-field" style="width:auto;">
                        <div class="file-field_one text-center hovergrey p-1" >
                            <span >
                                <?xml version="1.0" encoding="iso-8859-1"?>
                                <!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
                                <svg height="20px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                     viewBox="0 0 42 42" style="enable-background:new 0 0 42 42; margin-top: 0.5rem;" xml:space="preserve">
                                <polygon points="42,20 22,20 22,0 20,0 20,20 0,20 0,22 20,22 20,42 22,42 22,22 42,22 "/>
                                </svg>
                            </span>
                            <input name="photos" type="file" id="photos" multiple>
                        </div>
                    </div>
                {% else %}
                    <div class="grey-text mb-1" style="font-size:0.9rem;">К сожалению, вы не загрузили фотографий, но вы можете сделать это сейчас.</div>
                    <div class="file-field" style="width:auto;">
                        <div class="file-field_one text-center hovergrey p-1" >
                            <span>
                                <?xml version="1.0" encoding="iso-8859-1"?>
                                <!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
                                <svg height="20px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                     viewBox="0 0 42 42" style="enable-background:new 0 0 42 42; margin-top: 0.5rem;" xml:space="preserve">
                                <polygon points="42,20 22,20 22,0 20,0 20,20 0,20 0,22 20,22 20,42 22,42 22,22 42,22 "/>
                                </svg>
                            </span>
                            <input name="photos" type="file" id="photos" multiple>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-8 mt-2 float-left mb-4">
            <div class="card">
                {{ Changeform.about_user }}
            </div>
        </div>
    </form>
    <script>
    $(document).ready(function () {
        $("input#id_avatar").change(function() {
             renderImage(this.files[0])
        });
        $("input#photos").change(function() {
             for(var k=0; k < this.files.length ;k++){
                 renderImageM(this.files[k])
             }
        });
    })
    </script>
    <script>mask();</script>
{% endblock %}